version: "3.8"

volumes:
  mysql_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  mysql:
    image: "mysql:8"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    networks:
      - php_advanced
  php:
    #    image: "php:8.1-apache"
    #    environment:
    #      XDEBUG_MODE: "develop,debug"
    #      XDEBUG_CONFIG: client_host=host.docker.internal
    build:
      context: .docker/php
    # restart: always
    volumes:
      - .:/var/www/html
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/php/sites:/usr/local/apache/site-available
    ports:
      - "8080:80"
    networks:
      - php_advanced
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - php_advanced
    links:
      - mysql:mysql